### ISSUE TITLE
change epoch length to 30s

### ISSUE THREAD

**Issue by ubartsch** [alexander-malafeev/sleep-scoring#2]
Hi, 

I managed to get the scoring working using your previously trained model - but only when I use the default epoch length of 20s. 

I would prefer to do the scoring using 30 s epochs. Would I have to retrain the network?

Many thanks for a quick hint. 

BTW,  when I change the epoch length in the matlab prep script and in predict_split.py I get an error in load_weights:

```python
 During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\ulli\matlab\projects\sleep_scorer_zurich\main\predict_split.py", line 61, in <module>
    model.load_weights('./model_h_3ch.h5')

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\keras\engine\saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\keras\backend\tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\tensorflow_core\python\ops\variables.py", line 2067, in assign
    self._variable, value, use_locking=use_locking, name=name)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\tensorflow_core\python\ops\state_ops.py", line 227, in assign
    validate_shape=validate_shape)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\tensorflow_core\python\ops\gen_state_ops.py", line 66, in assign
    use_locking=use_locking, name=name)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1770, in __init__
    control_input_ops)

  File "C:\anaconda\envs\zurich_sleepscorer\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))

ValueError: Dimension 0 in both shapes must be equal, but are 513 and 257. Shapes are [513] and [257]. for 'Assign_140' (op: 'Assign') with input shapes: [513], [257].
```

**Comment by alexander-malafeev** [comment]
Hi!
Unfortunately it is not possible to change the length of the epoch without retraining the network. Our  training data was scored with 20s epochs. You can train your own network with custom epoch length, or you can convert scoring between different epoch length using procedure described in the paper.
